version: '3.9'

services:
    web:
        build:
          context: ./client
          dockerfile: Dockerfile-prod
        container_name: web
        ports:
            - "80:80"
            - "443:443"
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - ./client/data/certs:/etc/nginx/certs
            - ./client:/app
            - /app/node_modules
        depends_on: 
            - server
        networks: 
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
            - mongodbdata:/data/db
        networks:
            - backend

    server:
        build: ./server
        container_name: server
        ports:
            - "3010:5000"
        volumes:
            - ./server:/app 
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"
        depends_on: 
            - mongodb
        networks:
            - backend
            - frontend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local