version: '3.9'

services:
    web:
        build: ./client/web_faceid
        container_name: web
        restart: always
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./client/web_faceid:/user/src/app
            - /app/node_modules
        networks: 
            - frontend
            
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

    server:
        build: ./server
        container_name: server
        ports:
            - "80:5000"
        volumes:
            - ./server:/app 
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"    
        depends_on: 
            - mongodb
        networks:
            - backend
            - frontend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local